"""Curated seed rows for `/admin/seed` — realistic titles, venues, and copy."""

from __future__ import annotations

# Each blueprint includes status_hint: "open" | "full" | "live" → EventStatus 1, 2, 3

REALISTIC_EVENT_BLUEPRINTS: list[dict[str, object]] = [
    {
        "title": "Friday Night 5v5 Football — Silchar Turf",
        "sport_type": "Soccer",
        "venue_name": "Green Valley Sports Complex, Tarapur",
        "description": "All-weather turf, rolling subs every 8 minutes. Bring moulded studs.",
        "registration_mode": "team",
        "competition_format": "knockout",
        "duration_minutes": 90,
        "max_slots": 20,
        "skill_level": "intermediate",
        "price": 249.0,
        "age_group": "Open",
        "status_hint": "open",
    },
    {
        "title": "Weekend Futsal Cup — Indoor Arena",
        "sport_type": "Soccer",
        "venue_name": "City Indoor Futsal, Udarband Road",
        "description": "Fast indoor games, FIFA laws. Teams of 6 including keeper.",
        "registration_mode": "team",
        "competition_format": "knockout",
        "duration_minutes": 60,
        "max_slots": 12,
        "skill_level": "all",
        "price": 199.0,
        "age_group": "Open",
        "status_hint": "full",
    },
    {
        "title": "Cricket T20 Evening League",
        "sport_type": "Cricket",
        "venue_name": "Sonai Road Cricket Grounds",
        "description": "T20 format, white ball, 8 overs minimum. Umpires provided.",
        "registration_mode": "team",
        "competition_format": "league",
        "duration_minutes": 150,
        "max_slots": 16,
        "skill_level": "intermediate",
        "price": 1499.0,
        "age_group": "Open",
        "status_hint": "live",
    },
    {
        "title": "Tape-Ball Cricket — Floodlights",
        "sport_type": "Cricket",
        "venue_name": "Narsing High School Ground (evening)",
        "description": "Casual tape-ball matches. Tennis ball supplied.",
        "registration_mode": "team",
        "competition_format": "knockout",
        "duration_minutes": 120,
        "max_slots": 14,
        "skill_level": "beginner",
        "price": 99.0,
        "age_group": "Open",
        "status_hint": "open",
    },
    {
        "title": "Basketball Pick-Up Runs (Half Court)",
        "sport_type": "Basketball",
        "venue_name": "Don Bosco School Outdoor Court",
        "description": "4 teams rotate; first to 21 wins. Call picks on arrival.",
        "registration_mode": "team",
        "competition_format": "knockout",
        "duration_minutes": 120,
        "max_slots": 16,
        "skill_level": "all",
        "price": 0.0,
        "age_group": "Open",
        "status_hint": "open",
    },
    {
        "title": "3v3 Street Basketball — Sunset Session",
        "sport_type": "Basketball",
        "venue_name": "Gandhi Bag Public Courts",
        "description": "3v3 FIBA style, 10-minute games. Music and hydration station.",
        "registration_mode": "team",
        "competition_format": "knockout",
        "duration_minutes": 90,
        "max_slots": 12,
        "skill_level": "intermediate",
        "price": 129.0,
        "age_group": "18+",
        "status_hint": "full",
    },
    {
        "title": "Volleyball Mixed Doubles Social",
        "sport_type": "Volleyball",
        "venue_name": "NERIM Indoor Sports Hall",
        "description": "Rotating partners each set. Nets at standard height.",
        "registration_mode": "individual",
        "competition_format": "league",
        "duration_minutes": 90,
        "max_slots": 24,
        "skill_level": "beginner",
        "price": 79.0,
        "age_group": "Open",
        "status_hint": "open",
    },
    {
        "title": "Corporate Volleyball Round-Robin",
        "sport_type": "Volleyball",
        "venue_name": "Assam University Sports Block (guest slots)",
        "description": "6v6 indoor. Company teams welcome; bring jersey numbers.",
        "registration_mode": "team",
        "competition_format": "league",
        "duration_minutes": 120,
        "max_slots": 12,
        "skill_level": "intermediate",
        "price": 899.0,
        "age_group": "Open",
        "status_hint": "open",
    },
    {
        "title": "Badminton Singles Ladder — Morning",
        "sport_type": "Badminton",
        "venue_name": "Smash Point Badminton Academy",
        "description": "Feather shuttles, best of 3 to 21. Court 2 reserved for advanced.",
        "registration_mode": "individual",
        "competition_format": "league",
        "duration_minutes": 120,
        "max_slots": 16,
        "skill_level": "intermediate",
        "price": 179.0,
        "age_group": "Open",
        "status_hint": "live",
    },
    {
        "title": "Badminton Doubles Mixer",
        "sport_type": "Badminton",
        "venue_name": "Club Jannat Indoor Courts",
        "description": "Random doubles partnership each round. Great for networking.",
        "registration_mode": "individual",
        "competition_format": "league",
        "duration_minutes": 90,
        "max_slots": 20,
        "skill_level": "all",
        "price": 149.0,
        "age_group": "Open",
        "status_hint": "open",
    },
    {
        "title": "Tennis Coaching + Match Play",
        "sport_type": "Tennis",
        "venue_name": "Cachar Club Clay Courts",
        "description": "45 min drills with coach, then arranged singles sets.",
        "registration_mode": "individual",
        "competition_format": "knockout",
        "duration_minutes": 150,
        "max_slots": 8,
        "skill_level": "beginner",
        "price": 399.0,
        "age_group": "Open",
        "status_hint": "open",
    },
    {
        "title": "Tennis Singles Club Championship — Qualifiers",
        "sport_type": "Tennis",
        "venue_name": "Southern Club Hard Courts",
        "description": "ITF-style scoring. Balls and water included.",
        "registration_mode": "individual",
        "competition_format": "knockout",
        "duration_minutes": 180,
        "max_slots": 32,
        "skill_level": "competitive",
        "price": 499.0,
        "age_group": "Open",
        "status_hint": "full",
    },
    {
        "title": "Hockey 7s — Astroturf Trial",
        "sport_type": "Hockey",
        "venue_name": "District Stadium Practice Pitch",
        "description": "Shin guards mandatory. Goalkeepers rotate by quarter.",
        "registration_mode": "team",
        "competition_format": "knockout",
        "duration_minutes": 90,
        "max_slots": 14,
        "skill_level": "intermediate",
        "price": 199.0,
        "age_group": "Open",
        "status_hint": "open",
    },
    {
        "title": "Youth Baseball Intro & Scrimmage",
        "sport_type": "Baseball",
        "venue_name": "Rangirkhari Community Field",
        "description": "Equipment provided for U14; parent volunteers pitch.",
        "registration_mode": "team",
        "competition_format": "league",
        "duration_minutes": 120,
        "max_slots": 10,
        "skill_level": "beginner",
        "price": 0.0,
        "age_group": "U14",
        "status_hint": "open",
    },
    {
        "title": "Open Baseball Batting Cage + Field Day",
        "sport_type": "Baseball",
        "venue_name": "Silchar Railway Colony Ground",
        "description": "Batting cages 30 min slot, then informal fielding drills.",
        "registration_mode": "individual",
        "competition_format": "league",
        "duration_minutes": 180,
        "max_slots": 24,
        "skill_level": "all",
        "price": 89.0,
        "age_group": "Open",
        "status_hint": "open",
    },
    {
        "title": "Walking Football — 40+ Social League",
        "sport_type": "Soccer",
        "venue_name": "Gandhi Park Peripheral Track (side pitch)",
        "description": "Low-impact 7-a-side; no sliding tackles. Great cardio social session.",
        "registration_mode": "individual",
        "competition_format": "league",
        "duration_minutes": 60,
        "max_slots": 28,
        "skill_level": "all",
        "price": 0.0,
        "age_group": "40+",
        "status_hint": "open",
    },
    {
        "title": "Monsoon Cricket Friendly (Backup Date)",
        "sport_type": "Cricket",
        "venue_name": "Malugram Community Ground",
        "description": "Reserve date if prior week is rained out. WhatsApp group link after booking.",
        "registration_mode": "team",
        "competition_format": "knockout",
        "duration_minutes": 180,
        "max_slots": 12,
        "skill_level": "all",
        "price": 299.0,
        "age_group": "Open",
        "status_hint": "open",
    },
    {
        "title": "Sunday Morning Pickleball Intro",
        "sport_type": "Tennis",
        "venue_name": "River View Open Courts (converted lines)",
        "description": "Paddles and balls provided. Quick rules demo then rotation games.",
        "registration_mode": "individual",
        "competition_format": "league",
        "duration_minutes": 90,
        "max_slots": 16,
        "skill_level": "beginner",
        "price": 49.0,
        "age_group": "Open",
        "status_hint": "open",
    },
    {
        "title": "Inter-College Basketball Showcase",
        "sport_type": "Basketball",
        "venue_name": "G.C. College Indoor Arena",
        "description": "Exhibition games + talent scouts. Valid college ID at check-in.",
        "registration_mode": "team",
        "competition_format": "knockout",
        "duration_minutes": 180,
        "max_slots": 8,
        "skill_level": "competitive",
        "price": 0.0,
        "age_group": "U25",
        "status_hint": "live",
    },
    {
        "title": "Veterans Cricket 30-Overs — Friendly",
        "sport_type": "Cricket",
        "venue_name": "Sunamguri Village Oval",
        "description": "35+ preferred. Red ball, light-hearted laws. Tea break included.",
        "registration_mode": "team",
        "competition_format": "league",
        "duration_minutes": 240,
        "max_slots": 10,
        "skill_level": "intermediate",
        "price": 399.0,
        "age_group": "35+",
        "status_hint": "full",
    },
]
